#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="continuwuity"
prepare_service single

check_container_initialized
check_service_initialized init

case "${LOG_TYPE,,}" in
    file )
        exec_arg=">> ${LOG_PATH%/}/${LOG_FILE} 2>&1"
    ;;
    none )
        exec_arg="> /dev/null 2>&1"
    ;;
    * )
        exec_arg=""
    ;;
esac

liftoff

eval exec s6-setuidgid continuwuity \
    /usr/local/bin/conduwuit --config "${CONFIG_PATH%/}/${CONFIG_FILE}" ${exec_arg}
