#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

SETUP_TYPE=${SETUP_TYPE:-"AUTO"}

DATA_PATH=${DATA_PATH:-"/data/"}
CONFIG_PATH=${CONFIG_PATH:-"/config/"}
CONFIG_FILE=${CONFIG_FILE:-"conduwuit.toml"}

LISTEN_PORT=${LISTEN_PORT:-"8008"}
LISTEN_ADDRESS=${LISTEN_ADDRESS:-"0.0.0.0"}

LOG_TYPE=${LOG_TYPE:-"both"}
LOG_LEVEL=${LOG_LEVEL:-"info"}
LOG_PATH=${LOG_PATH:-"/logs/continuwuity/"}
LOG_FILE=${LOG_FILE:-"continuwuity.log"}

get_defaults_advanced
